#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build Raspberry Pi 2 Offical OpenWrt

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - 'rpi2-offical-openwrt.config'
#  schedule:
#    - cron: 0 18 * * *
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/*
        sudo swapoff /swapfile
        sudo rm -f /swapfile
        #docker rmi `docker images -q`
        #sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        curl -fsSL https://raw.githubusercontent.com/P3TERX/dotfiles/master/.bashrc >> ~/.bashrc
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

    - name: Clone Source Code
      env: 
        REPO_URL: https://github.com/openwrt/openwrt
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update Feeds
      run: |
       cd openwrt
       echo "src-git lienol https://github.com/Lienol/openwrt-package" >> feeds.conf.default
       ./scripts/feeds update -a

    - name: Install Feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load Custom Configuration
      env:
        CONFIG_FILE: 'rpi2-offical-openwrt.config'
        DIY_SH: 'offical-openwrt.sh'
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

#    - name: SSH Connection to Actions
#      uses: P3TERX/debugger-action@master

    - name: Download Package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-Thread Compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc)
        
    - name: Single-Thread Compile
      if: failure()
      run: |
        cd openwrt
        make -j1 V=s

    - name: Extract Gz Files
      run: |
        cd openwrt/bin/targets/brcm2708/bcm2709
        gzip -q -d openwrt-brcm2708-bcm2709-rpi-2-squashfs-factory.img.gz || true
        gzip -q -d openwrt-brcm2708-bcm2709-rpi-2-squashfs-sysupgrade.img.gz || true
        gzip -q -d openwrt-brcm2708-bcm2709-rpi-2-ext4-factory.img.gz || true
        gzip -q -d openwrt-brcm2708-bcm2709-rpi-2-ext4-sysupgrade.img.gz || true

    - name: Generate Sha256sum File
      run: |
        cd openwrt/bin/targets/brcm2708/bcm2709
        rm -rf sha256sums
        sha256sum openwrt* > sha256sums

    - name: Upload Config
      uses: actions/upload-artifact@master
      with:
        name: config.buildinfo
        path: openwrt/bin/targets/brcm2708/bcm2709/config.buildinfo
        
    - name: Upload Packages
      uses: actions/upload-artifact@master
      with:
        name: packages
        path: openwrt/bin/packages/arm_cortex-a7_neon-vfpv4/
        
    - name: Upload Packages Info
      uses: actions/upload-artifact@master
      with:
        name: openwrt-brcm2708-bcm2709-rpi-2.manifest
        path: openwrt/bin/targets/brcm2708/bcm2709/openwrt-brcm2708-bcm2709-rpi-2.manifest
        
    - name: Upload Kernel Packages
      uses: actions/upload-artifact@master
      with:
        name: kernel-packages
        path: openwrt/bin/targets/brcm2708/bcm2709/packages/
        
    - name: Upload RootFS Archive
      uses: actions/upload-artifact@master
      with:
        name: openwrt-brcm2708-bcm2709-rpi-2-rootfs.tar.gz
        path: openwrt/bin/targets/brcm2708/bcm2709/openwrt-brcm2708-bcm2709-rpi-2-rootfs.tar.gz
        
    - name: Upload SquashFS Factory Image
      uses: actions/upload-artifact@master
      with:
        name: openwrt-brcm2708-bcm2709-rpi-2-squashfs-factory.img
        path: openwrt/bin/targets/brcm2708/bcm2709/openwrt-brcm2708-bcm2709-rpi-2-squashfs-factory.img
        
    - name: Upload SquashFS Sysupgrade Image
      uses: actions/upload-artifact@master
      with:
        name: openwrt-brcm2708-bcm2709-rpi-2-squashfs-sysupgrade.img
        path: openwrt/bin/targets/brcm2708/bcm2709/openwrt-brcm2708-bcm2709-rpi-2-squashfs-sysupgrade.img
        
    - name: Upload Ext4 Factory Image
      uses: actions/upload-artifact@master
      with:
        name: openwrt-brcm2708-bcm2709-rpi-2-ext4-factory.img
        path: openwrt/bin/targets/brcm2708/bcm2709/openwrt-brcm2708-bcm2709-rpi-2-ext4-factory.img
        
    - name: Upload Ext4 Sysupgrade Image
      uses: actions/upload-artifact@master
      with:
        name: openwrt-brcm2708-bcm2709-rpi-2-ext4-sysupgrade.img
        path: openwrt/bin/targets/brcm2708/bcm2709/openwrt-brcm2708-bcm2709-rpi-2-ext4-sysupgrade.img
        
    - name: Upload Images Sha256sums
      uses: actions/upload-artifact@master
      with:
        name: sha256sums
        path: openwrt/bin/targets/brcm2708/bcm2709/sha256sums
